### ISSUE TITLE
📚[DOC]: Add example with diagnostic model

### ISSUE THREAD

**Issue by NickGeneva** [NVIDIA/earth2mip#119]
### How would you describe the priority of this documentation request

Critical (currently preventing usage)

### Is this for new documentation, or an update to existing docs?

New

### Describe the incorrect/future/missing documentation

Add an example demonstrating how to use diagnostic model
```[tasklist]
### Tasks
```

**Comment by nbren12** [comment]
would be great to show climatenet output in the docs.
