### ISSUE TITLE
🚀[FEA]: Refactor Perturbation Methods

### ISSUE THREAD

**Issue by NickGeneva** [NVIDIA/earth2mip#128]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

Refactor / Clean / Document Perturbation methods

- Pull into sub module
- Unit testings
- Doc strings
- User guide page on the topic

**Comment by nbren12** [comment]
nice idea.
