### ISSUE TITLE
rollback some of the API and implementation modifications in earth2mip/data

### ISSUE THREAD

**Issue by nbren12** [NVIDIA/earth2mip#135]
In summary,  would like to see the following changes before replacing the existing initial conditions:
- no outputting xarrays
- mostly revert the cds impementation to `initial_conditions.cds.DataSource`. sorry, but a lot of these changes are things I speciflcally undid in https://github.com/nbren12/earth2mip/commit/4b33f64cba2c4edf5ed67fe1dea69acfff4c84e8.
- for lexicons. Use the `cds.parse_channel` and ECMWF parameter IDs instead of dictionaries of strings.

_Originally posted by @nbren12 in https://github.com/NVIDIA/earth2mip/issues/132#issuecomment-1837034295_

**Comment by NickGeneva** [comment]
#170
