### ISSUE TITLE
🐛[BUG]: Fix Pangu Weather to work with Inferencer

### ISSUE THREAD

**Issue by NickGeneva** [NVIDIA/earth2mip#14]
### Version

Current

### On which installation method(s) does this occur?

Source

### Describe the issue

Instead of making Pangu have the same defunct interface as earth2mip.networks.Inference, run_inference should be modified to work with objects obeying the `earth2mip.time_loop.TimeLoop` interface.I

**Comment by nbren12** [comment]
Closed by #64
