### ISSUE TITLE
🚀[FEA]: Add Statistics

### ISSUE THREAD

**Issue by dallasfoster** [NVIDIA/earth2mip#141]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

It would be beneficial to have a easy to use class of statistics that do reductions on data. Assuming that the data carries around metadata with it, the reductions would operate on the data by operating over the dimensions in the metadata.

* It should be easy for a user to use the statistics.
* It should be easy for a user to define a custom statistic and use in their own workflow without adding a PR to the repo.
* The statistics should support reductions over ['initializations', 'ensemble'] and over domains. For reductions over domains, we would require (or request?) that users provides weights.
* The statistics should be able to support an 'update' method, where applicable. This might be dimension dependent. (updates for reductions over domains might not be initially supported.

**Comment by NickGeneva** [comment]
Closing based on internal discussions
