### ISSUE TITLE
🐛[BUG]: Inconsistency in Model Inferences with Modified Initial Conditions and Execution Date in 04_diagnostic_models Example

### ISSUE THREAD

**Issue by albetancurqu42** [NVIDIA/earth2mip#163]
### Version

main

### On which installation method(s) does this occur?

Source

### Describe the issue

Hello,

I'm currently working with the example script `04_diagnostic_models.py` and I've encountered an issue when making two specific modifications. The first change I made was using gfs instead of cds as the initial condition. The second change involved setting the execution date to 2024-01-10 00:00:00. Apart from these modifications, the code remains identical to the original example provided in your documentation.

The problem arises with the consistency of inferences obtained in both the original variables of the `fcn` model and the precipitation computed with `afno`. The results for all forecast horizons across all variables exhibit the following pattern:

Forecast results for the u10m variable across all forecast times and initial conditions:
![image](https://github.com/NVIDIA/earth2mip/assets/57238566/6522b938-f3ec-491a-b18e-4e8f007e40bd)
![image](https://github.com/NVIDIA/earth2mip/assets/57238566/9cb3d6de-2960-43e3-a07c-27c2a31114bd)

Forecast results for the tp variable across all forecast times and first forecast instance
![image](https://github.com/NVIDIA/earth2mip/assets/57238566/b76143dc-1ebe-4412-a123-145070a633ac)
![image](https://github.com/NVIDIA/earth2mip/assets/57238566/25b47def-5119-4a08-acc5-cb89bb65dc83)

The reason for raising this issue is that variables not related to the `afno` model are also being affected. Interestingly, when I run the same example under the initial conditions, I can reproduce the results shown in the example from the documentation. Similarly, executing it with `cds` but for the date 2024-01-10 00:00:00, I obtained consistent results.

Could you please provide some insight into why these discrepancies are occurring and any potential solutions?

Thank you for your assistance.

### Environment details

```shell
+ Environment location: ec2 AWS, miniconda, Tesla T4
```

**Comment by nbren12** [comment]
Thanks for opening the issue @albetancurqu42. Could you share the complete example script you are trying to run?

Could be an issue with the GFS DataSource, this hasn't been used as much.

**Comment by nbren12** [comment]
cc @NickGeneva

**Comment by albetancurqu42** [comment]
Resolved the issue when using GFS by addressing the multiplication of geopotential height with gravity to obtain geopotential. The root cause was an incorrect if statement failing to check when the variable is "Z", preventing proper processing. 

Additionally, identified an error in the GFS beta function, specifically in beta.lexicon.gfs.py, related to a typographical error in the naming of the u100m variable in the original data source labels.
