### ISSUE TITLE
🐛[BUG]: Running inference_ensemble with multiple ensemble members per rank causes perturbations to be applied multiple times

### ISSUE THREAD

**Issue by ankurmahesh** [NVIDIA/earth2mip#164]
### Version

source - main @ git commit: ebd86637ec853c11e9ff5e717b053351c740e526

### On which installation method(s) does this occur?

Source

### Describe the issue

When running 32 ensemble members with 1 rank, the later ensemble members have the perturbation applied multiple times.   So the second ensemble member on each rank has a perturbation applied twice.  The third ensemble member has a perturbation applied three times.  Etc.   Is this behavior expected?

This could make the magnitude of the perturbations very large, unless there is some perturbation magnitude normalization applied later.

Using the correlated IC perturbation method with noise amplitude 0.05, the first ensemble member has this magnitude of perturbation: 
![image](https://github.com/NVIDIA/earth2mip/assets/15190307/ddeb71d8-4811-4742-8fd4-987799d0b0f8)

The 15th ensemble member has this perturbation:
![image](https://github.com/NVIDIA/earth2mip/assets/15190307/8489da74-1c81-4b45-ab7c-be0e5e7fafcd)

And the 31st ensemble member has this perturbation:
![image](https://github.com/NVIDIA/earth2mip/assets/15190307/32d507d0-365a-41e0-b27b-0d89c7c6f88c)

I think there could be two causes:

1. x is being overwritten by the perturb method [here](https://github.com/NVIDIA/earth2mip/blob/main/earth2mip/inference_ensemble.py#L104), so as the loop moves forward, the perturbed x gets perturbed again, instead of the original x getting perturbed.
2. x is mutable, and x is being modified [here](https://github.com/NVIDIA/earth2mip/blob/main/earth2mip/inference_ensemble.py#L256).

**Comment by nbren12** [comment]
How strange. Thanks for reporting this issue @ankurmahesh.
