### ISSUE TITLE
📚[DOC]: Information on Local Data for inference ensembles

### ISSUE THREAD

**Issue by david5010** [NVIDIA/earth2mip#194]
### How would you describe the priority of this documentation request

Medium

### Is this for new documentation, or an update to existing docs?

New

### Describe the incorrect/future/missing documentation

The documentation lacks information for setting up the initial conditions. For GFS, IFS and CDS, it's rather clear. However, I'm having a lot of trouble understanding the hrmip and hdf5 files. I'm not sure how to use them, but I want to use my local data for inference_ensembles. Any help would be much appreciated!

**Comment by nbren12** [comment]
The hdf5 and hrmip files are somewhat specific to our internal datasets. 

If you have your own local data format, I would recommend writing your own subclass of 
API: https://github.com/NVIDIA/earth2mip/blob/86b11fe4ba2f19641802112e8b0ba6b962123130/earth2mip/initial_conditions/base.py#L26.

You can then use earth2mip as a library with your own datasource. 

Does that make sense?

**Comment by david5010** [comment]
Ohh I see, thank you!
