### ISSUE TITLE
get_model giving ssl Network is unreachable error

### ISSUE THREAD

**Issue by manmeet3591** [NVIDIA/earth2mip#197]
I have a code that was running for months and now get_model is giving an ssl error. 

![Image](https://github.com/user-attachments/assets/aaeb441d-e54b-4b89-bb32-d8fdb3b8e799)

**Comment by manmeet3591** [comment]
@nbren12

**Comment by nbren12** [comment]
Hi. Seems like a network issue when downloading the graphcast checkpoint. Not sure we can do anything on the earth2mip side about that.
