### ISSUE TITLE
📚[DOC]: Enhance config documentation / examples

### ISSUE THREAD

**Issue by NickGeneva** [NVIDIA/earth2mip#37]
### How would you describe the priority of this documentation request

Critical (currently preventing usage)

### Is this for new documentation, or an update to existing docs?

Update

### Describe the incorrect/future/missing documentation

Improve config documentation to show options and also some more samples than what the notebooks provides

**Comment by nbren12** [comment]
Closing since it is not specific. We can make issues for specific documentation needs.
