### ISSUE TITLE
🚀[FEA]: Add caching capabilities to data sources

### ISSUE THREAD

**Issue by NickGeneva** [NVIDIA/earth2mip#38]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

Add ability for data-sources to cache the data locally on the machine and reuse it, instead of always downloading.

**Comment by nbren12** [comment]
my graphcast PR contains CDS caching.

**Comment by NickGeneva** [comment]
This was merged https://github.com/NVIDIA/earth2mip/pull/76
