### ISSUE TITLE
🚀[FEA]: Using noise injection between steps as model perturbation

### ISSUE THREAD

**Issue by yairchn** [NVIDIA/earth2mip#51]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

To account for model uncertainties in ensemble forecasting we need to enable perturbing the model. The simplest way to achieve this is injecting noise between steps. It is important that the type of noise injection and amplitude will be determined from the config file.

**Comment by nbren12** [comment]
We agreed this should just be a an example script/notebook for one model right now.

**Comment by NickGeneva** [comment]
Closing with PR: https://github.com/NVIDIA/earth2mip/pull/77
