### ISSUE TITLE
🚀[FEA]: Enable MyPy Type checking in pre-commit / CI

### ISSUE THREAD

**Issue by NickGeneva** [NVIDIA/earth2mip#52]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

Enable static type checking in repo.

https://mypy-lang.org/

**Comment by YichengDWu** [comment]
I fully support this proposal. Furthermore, I believe it would be even more beneficial to adopt the [new syntax](https://peps.python.org/pep-0585/).

**Comment by nbren12** [comment]
> I fully support this proposal. Furthermore, I believe it would be even more beneficial to adopt the [new syntax](https://peps.python.org/pep-0585/).

This would require removing support for python 3.8 and older. I'm not opposed...many platforms have moved on, I think colab is on 3.10, [ubuntu 22.04](https://packages.ubuntu.com/jammy/python3) is too.
