### ISSUE TITLE
🐛[BUG]: Get Pangu models to functions with GFS

### ISSUE THREAD

**Issue by NickGeneva** [NVIDIA/earth2mip#56]
### Version

main

### Describe the issue

Presently GFS does not support Pangu channel set. Should probably just add it with the channel set for now and update to more general schema later

**Comment by nbren12** [comment]
Would be nice to generalize the GFS data source to work with any list of channel names like the cds api data source does. Maybe some code could be reused since GFS is grib as well.

If this is not urgent, would be preferable to have the more general solution.

**Comment by nbren12** [comment]
working on a refactor that will fix this.
