### ISSUE TITLE
🚀[FEA]: NGC File system for ZIP model package files on NGC 

### ISSUE THREAD

**Issue by NickGeneva** [NVIDIA/earth2mip#57]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

The File system should support the use of NGC model registry natively and download files with urls such as `ngc://model_url`. The existing NGC packages should then be cleaned up to use this feature.

This includes then cleaning up the built in packages.

Some additional discussion is found here: https://github.com/NVIDIA/earth2mip/pull/55

**Comment by nbren12** [comment]
Aren't we using the modulus.utils.filesystem? 

If so, this is an upstream issue.
If not, should we start using modulus.utils.filesystem and remove earth2mip.fileystem?

**Comment by NickGeneva** [comment]
Merged upstream...

**Comment by NickGeneva** [comment]
Current system works fine with the Model registry, closing for now
