### ISSUE TITLE
🐛[BUG]: Earth-2 MIP should run on CPU mode

### ISSUE THREAD

**Issue by NickGeneva** [NVIDIA/earth2mip#59]
### Version

main

### On which installation method(s) does this occur?

Source

### Describe the issue

Presently Earth-2 MIP fails for CPU runs because of some hard coded cuda() commands which should be swapped for .to(device) which should allow for CPU inference.

**Comment by nbren12** [comment]
I'm in favor, but are there any models that are usable on CPU?

**Comment by NickGeneva** [comment]
Good point, DLWP and the FCN should be fine... Pangu I think should be able as I'm guess but I have not tried, its ONNX so as long as it just has operators that are supported by the CPU runtime should be fine. FCNv2 would also need a test, but I'm not losing sleep over it. 

If anything, this restriction should be imposed by the model's load function if needed.

**Comment by nbren12** [comment]
I tracked down some of these issues in #76. I am not sure if there are others, but this issue doesn't refer to any specific bug. If someone notices a specific bug, then we can open issue for that.
